issue-tracker:
  api:
    version: v1
    title: Issue Tracker API
    description: Issue Tracker sample application
    external-docs:
      description: Issue Tracker GitHub repo
      url: https://github.com/mpatapenka/IssueTracker


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/issue_tracker_dev
    username: issue_tracker_admin
    password: secret

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate.default_schema: "`${spring.flyway.schemas}`"

  flyway:
    schemas: issue_tracker


springdoc:
  writer-with-default-pretty-printer: true
  show-actuator: true
  api-docs:
    path: /${issue-tracker.api.version}/api-docs
  swagger-ui:
    path: /${issue-tracker.api.version}/swagger-ui.html
    tags-sorter: alpha
    operations-sorter: method
    disable-swagger-default-url: true
    layout: BaseLayout
    display-request-duration: true


logging:
  level:
    root: INFO
    org.mpatapenka.issuetracker.api: DEBUG