<%@ taglib uri="http://tiles.apache.org/tags-tiles" prefix="tiles" %>

<tiles:insertDefinition name="hftemplate">
    <tiles:putAttribute name="content">
        <div class="content-header">
            System Dashboard
        </div>
        <div class="content-layout">
            <div class="content-panel">
                <div class="panel-header">
                    Activity Stream
                </div>
                <div class="panel-content">
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    <a href="#" class="button">
                        <span class="btn-panel">Show more...</span>
                    </a>
                </div>
            </div>
            <div class="content-panel">
                <div class="panel-header">
                    Assigned to Me
                </div>
                <div class="panel-content">
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                    some issues<br>
                </div>
            </div>
        </div>
    </tiles:putAttribute>
</tiles:insertDefinition>