-- Tables initialization
create table employee
(
    id          bigint generated by default as identity primary key,
    first_name  varchar(50)  not null,
    last_name   varchar(50)  not null,
    username    varchar(20)  not null unique,
    password    varchar(100) not null,
    position_id bigint       not null
);

create table employee_position
(
    id   bigint generated by default as identity primary key,
    name varchar(100) not null unique
);

create table employee_role
(
    id   bigint generated by default as identity primary key,
    name varchar(15) not null unique
);

create table employee_membership
(
    id          bigint generated by default as identity primary key,
    employee_id bigint not null,
    project_id  bigint not null,
    role_id     bigint not null
);

create table project
(
    id          bigint generated by default as identity primary key,
    name        varchar(100) not null unique,
    description text
);

create table task
(
    id                    bigint generated by default as identity primary key,
    project_id            bigint    not null,
    status_id             bigint    not null,
    assigned_to           bigint,
    description           text      not null,
    scheduled_start_at    timestamp not null,
    scheduled_complete_at timestamp not null,
    started_at            timestamp,
    completed_at          timestamp
);

create table task_status
(
    id   bigint generated by default as identity primary key,
    name varchar(15) not null unique
);

create table attachment
(
    id          bigint generated by default as identity primary key,
    task_id     bigint       not null,
    file_name   varchar(255) not null,
    file_size   bigint       not null,
    file_path   text         not null,
    description text
);

create table task_activity
(
    id           bigint generated by default as identity primary key,
    task_id      bigint    not null,
    added_by     bigint    not null,
    started_at   timestamp not null default now(),
    completed_at timestamp not null,
    comment      text
);


-- References initialization
alter table employee
    add foreign key (position_id) references employee_position (id);

alter table employee_membership
    add foreign key (employee_id) references employee (id),
    add foreign key (project_id) references project (id),
    add foreign key (role_id) references employee_role (id);

alter table task
    add foreign key (project_id) references project (id),
    add foreign key (status_id) references task_status (id),
    add foreign key (assigned_to) references employee (id);

alter table attachment
    add foreign key (task_id) references task (id);

alter table task_activity
    add foreign key (task_id) references task (id),
    add foreign key (added_by) references employee (id);


-- Indexes initialization
create index on employee_membership (employee_id, project_id);

create index on task (project_id, status_id, assigned_to);

create index on task_activity (task_id, added_by, started_at);