-- Tables initialization
create table employee
(
    id          int generated by default as identity primary key,
    first_name  varchar(50) not null,
    last_name   varchar(50) not null,
    username    varchar(10) not null unique,
    password    varchar(60) not null,
    position_id int         not null
);

create table employee_position
(
    id   int generated by default as identity primary key,
    name varchar(100) not null unique
);

create table project_role
(
    id   int generated by default as identity primary key,
    name varchar(15) not null unique,
    code varchar(20) not null unique
);

create table project_membership
(
    id          int generated by default as identity primary key,
    employee_id int not null,
    project_id  int not null,
    role_id     int not null
);

create table project
(
    id          int generated by default as identity primary key,
    name        varchar(100) not null unique,
    description text
);

create table task
(
    id                    int generated by default as identity primary key,
    project_id            int          not null,
    status_id             int          not null,
    assigned_to           int,
    summary               varchar(100) not null,
    description           text,
    scheduled_start_at    timestamp    not null,
    scheduled_complete_at timestamp    not null,
    started_at            timestamp,
    completed_at          timestamp
);

create table task_status
(
    id   int generated by default as identity primary key,
    name varchar(15) not null unique
);

create table task_attachment
(
    id          int generated by default as identity primary key,
    task_id     int          not null,
    file_name   varchar(255) not null,
    file_size   bigint       not null,
    file_path   varchar(510) not null,
    description text
);

create table task_activity
(
    id           int generated by default as identity primary key,
    task_id      int       not null,
    added_by     int       not null,
    started_at   timestamp not null default now(),
    completed_at timestamp not null,
    comment      text
);


-- References initialization
alter table employee
    add foreign key (position_id) references employee_position (id);

alter table project_membership
    add foreign key (employee_id) references employee (id);
alter table project_membership
    add foreign key (project_id) references project (id);
alter table project_membership
    add foreign key (role_id) references project_role (id);

alter table task
    add foreign key (project_id) references project (id);
alter table task
    add foreign key (status_id) references task_status (id);
alter table task
    add foreign key (assigned_to) references employee (id);

alter table task_attachment
    add foreign key (task_id) references task (id);

alter table task_activity
    add foreign key (task_id) references task (id);
alter table task_activity
    add foreign key (added_by) references employee (id);


-- Indexes initialization
create unique index on project_membership (project_id, employee_id, role_id);

create index on task_attachment (task_id);

create index on task (project_id, status_id, assigned_to);

create index on task_activity (task_id, added_by, started_at, completed_at);